name: 'Create DMG and Upload to Release'
description: 'Generates DMG files using jDeploy and uploads them to a GitHub release'
author: 'Steve Hannah'
inputs:
  jdeploy_version:
    description: 'The version of jDeploy to use. Prefix with "git://" to build from a Git branch, tag, or commit hash.'
    default: 'git://master'
    required: true
  release_tag:
    description: 'The tag name of the release to upload the DMG to. If not specified, the action will attempt to determine it automatically.'
    required: false
  github_token:
    description: 'GitHub token for authentication'
    required: true
  target_repository:
    description: Optional target repository where to publish releases.
    required: false
    default: ${{ github.repository }}
  notarization_password:
    description: 'Notarization password for macOS code signing'
    required: false
  developer_id:
    description: 'Apple Developer ID for macOS code signing'
    required: false
  developer_team_id:
    description: 'Apple Developer Team ID for macOS code signing'
    required: false
  developer_certificate_name:
    description: 'Certificate name for macOS code signing'
    required: false
  developer_certificate_p12_base64:
    description: 'Base64-encoded P12 certificate for macOS code signing'
    required: false
  developer_certificate_password:
    description: 'Password for the P12 certificate'
    required: false

runs:
  using: 'composite'
  steps:

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    # Conditional step to set up Java if jdeploy_version starts with git://
    - name: Set up Java for jDeploy
      if: ${{ startsWith(inputs.jdeploy_version, 'git://') }}
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
      id: setup-java-jdeploy

    - name: Set jDeploy Source Environment Variable
      shell: bash
      run: echo "JDEPLOY_SOURCE=https://github.com/${{ inputs.target_repository }}" >> $GITHUB_ENV

    # Corrected Extract jDeploy Version Step
    - name: Extract jDeploy Version
      shell: bash
      run: |
        jdeploy_version="${{ inputs.jdeploy_version }}"
        if [[ "$jdeploy_version" == git://* ]]; then
          JDEPLOY_REF="${jdeploy_version#git://}"
          echo "JDEPLOY_REF=$JDEPLOY_REF" >> $GITHUB_ENV
          echo "JDEPLOY_EXEC=jdeploy" >> $GITHUB_ENV
        else
          echo "JDEPLOY_VERSION=$jdeploy_version" >> $GITHUB_ENV
          echo "JDEPLOY_EXEC=jdeploy@$jdeploy_version" >> $GITHUB_ENV
        fi

    # Determine release_tag if not specified
    - name: Determine Release Tag
      shell: bash
      run: |
        if [ -z "${{ inputs.release_tag }}" ]; then
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            RELEASE_TAG="${GITHUB_REF_NAME}"
          elif [[ "$GITHUB_REF_TYPE" == "branch" ]]; then
            RELEASE_TAG="${GITHUB_REF_NAME}"
          else
            echo "Cannot determine release tag from GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
            exit 1
          fi
        else
          RELEASE_TAG="${{ inputs.release_tag }}"
        fi
        echo "Using release tag: $RELEASE_TAG"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

    # Checkout jDeploy source if using git:// version
    - name: Checkout jDeploy Source
      if: ${{ startsWith(inputs.jdeploy_version, 'git://') }}
      shell: bash
      run: |
        git clone https://github.com/shannah/jdeploy.git jdeploy-source
        cd jdeploy-source
        git checkout "$JDEPLOY_REF"

    # Build jDeploy from Source
    - name: Build jDeploy from Source
      if: ${{ startsWith(inputs.jdeploy_version, 'git://') }}
      shell: bash
      run: |
        # Use isolated JAVA_HOME if set
        if [ -n "${{ steps.setup-java-jdeploy.outputs.path }}" ]; then
          export JAVA_HOME="${{ steps.setup-java-jdeploy.outputs.path }}"
          export PATH="$JAVA_HOME/bin:$PATH"
        fi
        cd jdeploy-source/shared
        mvn clean install -DskipTests --batch-mode --no-transfer-progress
        cd ../cli
        mvn clean package -DskipTests --batch-mode --no-transfer-progress
        npm install
        npm link

    # Install jDeploy from npm if not using git:// version
    - name: Install jDeploy from npm
      if: ${{ !startsWith(inputs.jdeploy_version, 'git://') }}
      shell: bash
      run: npm install -g jdeploy@${{ inputs.jdeploy_version }}

    - name: Set jdeploy.jdeployVersion for Branch
      if: ${{ github.ref_type == 'branch' }}
      shell: bash
      run: |
        if [[ "${{ startsWith(inputs.jdeploy_version, 'git://') }}" == "true" ]]; then
          npm pkg set jdeploy.jdeployVersion='latest'
        else
          npm pkg set jdeploy.jdeployVersion='${{ inputs.jdeploy_version }}'
        fi
        npm pkg set version="0.0.0-${{ github.ref_name }}"
        npm pkg set jdeploy.commitHash="$GITHUB_SHA"
      env:
        GH_TOKEN: ${{ github.actor }}:${{ inputs.github_token }}

    - name: Sanitize version name
      shell: bash
      if: ${{ github.ref_type == 'tag' }}
      run: |
        TAG_VERSION=${{ github.ref_name }}
        if [[ $TAG_VERSION} = v* ]]; then
          echo "TAG_VERSION=${TAG_VERSION:1}" >> $GITHUB_ENV
        else
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
        fi
    - name: Prepare Installer Bundles for Branch
      if: ${{ github.ref_type == 'branch' }}
      shell: bash
      run: |
        npm pkg set version="0.0.0-${{ github.ref_name }}"
        if [[ "${{ startsWith(inputs.jdeploy_version, 'git://') }}" == "true" ]]; then
          npm pkg set jdeploy.jdeployVersion='latest'
        else
          npm pkg set jdeploy.jdeployVersion='${{ inputs.jdeploy_version }}'
        fi
        npm pkg set jdeploy.commitHash="$GITHUB_SHA"
      env:
        GH_TOKEN: ${{ github.actor }}:${{ inputs.github_token }}

    - name: Prepare Installer Bundles for Tag
      if: ${{ github.ref_type == 'tag' }}
      shell: bash
      run: |
        npm pkg set version="$TAG_VERSION"
        if [[ "${{ startsWith(inputs.jdeploy_version, 'git://') }}" == "true" ]]; then
          npm pkg set jdeploy.jdeployVersion='latest'
        else
          npm pkg set jdeploy.jdeployVersion='${{ inputs.jdeploy_version }}'
        fi
        npm pkg set jdeploy.commitHash="$GITHUB_SHA"
        npm pkg set jdeploy.gitTag="${{ github.ref_name }}"
      env:
        GH_TOKEN: ${{ github.actor }}:${{ inputs.github_token }}

    # Install MacOS Certificates if provided
    - name: Install MacOS Certificates
      if: ${{ inputs.developer_certificate_p12_base64 && inputs.developer_certificate_password }}
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ inputs.developer_certificate_p12_base64 }}
        p12-password: ${{ inputs.developer_certificate_password }}
        keychain: 'build'

    - name: Set Code Signing Environment Variables
      shell: bash
      run: |
        echo "Setting code signing environment variables"
        # Set each environment variable if the input is provided
        if [ -n "${{ inputs.notarization_password }}" ]; then
          echo "JDEPLOY_MAC_NOTARIZATION_PASSWORD=${{ inputs.notarization_password }}" >> $GITHUB_ENV
        fi
        if [ -n "${{ inputs.developer_id }}" ]; then
          echo "JDEPLOY_MAC_DEVELOPER_ID=${{ inputs.developer_id }}" >> $GITHUB_ENV
        fi
        if [ -n "${{ inputs.developer_team_id }}" ]; then
          echo "JDEPLOY_MAC_DEVELOPER_TEAM_ID=${{ inputs.developer_team_id }}" >> $GITHUB_ENV
        fi
        if [ -n "${{ inputs.developer_certificate_name }}" ]; then
          echo "JDEPLOY_MAC_DEVELOPER_CERTIFICATE_NAME=${{ inputs.developer_certificate_name }}" >> $GITHUB_ENV
        fi

    - name: Enable code-signing
      shell: bash
      if: ${{ inputs.developer_certificate_name && inputs.developer_certificate_p12_base64 && inputs.developer_certificate_password }}
      run: |
        npm pkg set jdeploy.codesign=true --json

    - name: Enable notarization
      shell: bash
      if: ${{ inputs.developer_id && inputs.notarization_password }}
      run: |
        npm pkg set jdeploy.notarize=true --json

    # Build DMGs using jDeploy
    - name: Build DMGs
      shell: bash
      run: |
        ${{ env.JDEPLOY_EXEC }} dmg
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    # Install jq (needed for JSON parsing)
    - name: Install jq
      shell: bash
      run: brew install jq

    # Upload DMGs to Release
    - name: Upload DMGs to Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        # Get release ID
        release_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$RELEASE_TAG")

        release_id=$(echo "$release_response" | jq -r .id)

        if [ "$release_id" == "null" ] || [ -z "$release_id" ]; then
          echo "Release not found for tag '$RELEASE_TAG'"
          exit 1
        fi

        for dmg_file in ./jdeploy/installers/*.dmg; do
          echo "Uploading $dmg_file to release ID $release_id"
          asset_name=$(basename "$dmg_file")
          asset_name_encoded=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$asset_name")

          # Delete existing asset if it exists
          existing_asset_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/$release_id/assets" \
            | jq -r ".[] | select(.name == \"$asset_name\") | .id")

          if [ -n "$existing_asset_id" ] && [ "$existing_asset_id" != "null" ]; then
            echo "Deleting existing asset with ID $existing_asset_id"
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/assets/$existing_asset_id"
          fi

          # Upload the file
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/x-apple-diskimage" \
            --data-binary @"$dmg_file" \
            "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/$release_id/assets?name=$asset_name_encoded"
        done
    
